// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client/index.js';
import type { FindPetsData, FindPetsResponses, FindPetsErrors, AddPetData, AddPetResponses, AddPetErrors, GetNotDefinedData, GetNotDefinedResponses, GetNotDefinedErrors, PostNotDefinedData, PostNotDefinedResponses, PostNotDefinedErrors, DeletePetData, DeletePetResponses, DeletePetErrors, FindPetByIdData, FindPetByIdResponses, FindPetByIdErrors, FindPaginatedPetsData, FindPaginatedPetsResponses, FindCursorBasedPetsData, FindCursorBasedPetsResponses } from './types.gen.js';
import { client as _heyApiClient } from './client.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns all pets from the system that the user has access to
 * Nam sed condimentum est. Maecenas tempor sagittis sapien, nec rhoncus sem sagittis sit amet. Aenean at gravida augue, ac iaculis sem. Curabitur odio lorem, ornare eget elementum nec, cursus id lectus. Duis mi turpis, pulvinar ac eros ac, tincidunt varius justo. In hac habitasse platea dictumst. Integer at adipiscing ante, a sagittis ligula. Aenean pharetra tempor ante molestie imperdiet. Vivamus id aliquam diam. Cras quis velit non tortor eleifend sagittis. Praesent at enim pharetra urna volutpat venenatis eget eget mauris. In eleifend fermentum facilisis. Praesent enim enim, gravida ac sodales sed, placerat id erat. Suspendisse lacus dolor, consectetur non augue vel, vehicula interdum libero. Morbi euismod sagittis libero sed lacinia.
 *
 * Sed tempus felis lobortis leo pulvinar rutrum. Nam mattis velit nisl, eu condimentum ligula luctus nec. Phasellus semper velit eget aliquet faucibus. In a mattis elit. Phasellus vel urna viverra, condimentum lorem id, rhoncus nibh. Ut pellentesque posuere elementum. Sed a varius odio. Morbi rhoncus ligula libero, vel eleifend nunc tristique vitae. Fusce et sem dui. Aenean nec scelerisque tortor. Fusce malesuada accumsan magna vel tempus. Quisque mollis felis eu dolor tristique, sit amet auctor felis gravida. Sed libero lorem, molestie sed nisl in, accumsan tempor nisi. Fusce sollicitudin massa ut lacinia mattis. Sed vel eleifend lorem. Pellentesque vitae felis pretium, pulvinar elit eu, euismod sapien.
 *
 */
export const findPets = <ThrowOnError extends boolean = false>(options?: Options<FindPetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindPetsResponses, FindPetsErrors, ThrowOnError>({
        url: '/pets',
        ...options
    });
};

/**
 * Creates a new pet in the store. Duplicates are allowed
 */
export const addPet = <ThrowOnError extends boolean = false>(options: Options<AddPetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddPetResponses, AddPetErrors, ThrowOnError>({
        url: '/pets',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * This path is not fully defined.
 * @deprecated
 */
export const getNotDefined = <ThrowOnError extends boolean = false>(options?: Options<GetNotDefinedData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetNotDefinedResponses, GetNotDefinedErrors, ThrowOnError>({
        url: '/not-defined',
        ...options
    });
};

/**
 * This path is not defined at all.
 * @deprecated
 */
export const postNotDefined = <ThrowOnError extends boolean = false>(options?: Options<PostNotDefinedData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostNotDefinedResponses, PostNotDefinedErrors, ThrowOnError>({
        url: '/not-defined',
        ...options
    });
};

/**
 * deletes a single pet based on the ID supplied
 */
export const deletePet = <ThrowOnError extends boolean = false>(options: Options<DeletePetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeletePetResponses, DeletePetErrors, ThrowOnError>({
        url: '/pets/{id}',
        ...options
    });
};

/**
 * Returns a user based on a single ID, if the user does not have access to the pet
 */
export const findPetById = <ThrowOnError extends boolean = false>(options: Options<FindPetByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<FindPetByIdResponses, FindPetByIdErrors, ThrowOnError>({
        url: '/pets/{id}',
        ...options
    });
};

/**
 * Returns paginated pets from the system that the user has access to
 *
 */
export const findPaginatedPets = <ThrowOnError extends boolean = false>(options?: Options<FindPaginatedPetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindPaginatedPetsResponses, unknown, ThrowOnError>({
        url: '/paginated-pets',
        ...options
    });
};

/**
 * Returns cursor-based pets from the system that the user has access to
 *
 */
export const findCursorBasedPets = <ThrowOnError extends boolean = false>(options?: Options<FindCursorBasedPetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindCursorBasedPetsResponses, unknown, ThrowOnError>({
        url: '/cursor-based-pets',
        ...options
    });
};