// This file is auto-generated by @hey-api/openapi-ts

export type Pet = NewPet & {
    id: number;
};

export type NewPet = {
    name: string;
    tag?: string;
};

export type _Error = {
    code: number;
    message: string;
};

export type FindPetsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * tags to filter by
         */
        tags?: Array<string>;
        /**
         * maximum number of results to return
         */
        limit?: number;
    };
    url: '/pets';
};

export type FindPetsErrors = {
    /**
     * unexpected error
     */
    default: _Error;
};

export type FindPetsError = FindPetsErrors[keyof FindPetsErrors];

export type FindPetsResponses = {
    /**
     * pet response
     */
    200: Array<Pet>;
};

export type FindPetsResponse = FindPetsResponses[keyof FindPetsResponses];

export type AddPetData = {
    /**
     * Pet to add to the store
     */
    body: NewPet;
    path?: never;
    query?: never;
    url: '/pets';
};

export type AddPetErrors = {
    /**
     * unexpected error
     */
    default: _Error;
};

export type AddPetError = AddPetErrors[keyof AddPetErrors];

export type AddPetResponses = {
    /**
     * pet response
     */
    200: Pet;
};

export type AddPetResponse = AddPetResponses[keyof AddPetResponses];

export type GetNotDefinedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/not-defined';
};

export type GetNotDefinedErrors = {
    /**
     * unexpected error
     */
    default: unknown;
};

export type GetNotDefinedResponses = {
    /**
     * unexpected error
     */
    default: unknown;
};

export type PostNotDefinedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/not-defined';
};

export type PostNotDefinedErrors = {
    /**
     * unexpected error
     */
    default: unknown;
};

export type PostNotDefinedResponses = {
    /**
     * unexpected error
     */
    default: unknown;
};

export type DeletePetData = {
    body?: never;
    path: {
        /**
         * ID of pet to delete
         */
        id: number;
    };
    query?: never;
    url: '/pets/{id}';
};

export type DeletePetErrors = {
    /**
     * unexpected error
     */
    default: _Error;
};

export type DeletePetError = DeletePetErrors[keyof DeletePetErrors];

export type DeletePetResponses = {
    /**
     * pet deleted
     */
    204: void;
};

export type DeletePetResponse = DeletePetResponses[keyof DeletePetResponses];

export type FindPetByIdData = {
    body?: never;
    path: {
        /**
         * ID of pet to fetch
         */
        id: number;
    };
    query?: never;
    url: '/pets/{id}';
};

export type FindPetByIdErrors = {
    /**
     * unexpected error
     */
    default: _Error;
};

export type FindPetByIdError = FindPetByIdErrors[keyof FindPetByIdErrors];

export type FindPetByIdResponses = {
    /**
     * pet response
     */
    200: Pet;
};

export type FindPetByIdResponse = FindPetByIdResponses[keyof FindPetByIdResponses];

export type FindPaginatedPetsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number
         */
        page?: number;
        /**
         * tags to filter by
         */
        tags?: Array<string>;
        /**
         * maximum number of results to return
         */
        limit?: number;
    };
    url: '/paginated-pets';
};

export type FindPaginatedPetsResponses = {
    /**
     * pet response
     */
    200: {
        pets?: Array<Pet>;
        nextPage?: number;
    };
};

export type FindPaginatedPetsResponse = FindPaginatedPetsResponses[keyof FindPaginatedPetsResponses];

export type ClientOptions = {
    baseUrl: 'http://petstore.swagger.io/api' | (string & {});
};